/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    cities: City;
    places: Place;
    'pricing-plans': PricingPlan;
    events: Event;
    organizers: Organizer;
    inquiries: Inquiry;
    'claim-requests': ClaimRequest;
    reviews: Review;
    'attribute-groups': AttributeGroup;
    attributes: Attribute;
    pages: Page;
    posts: Post;
    'post-categories': PostCategory;
    'newsletter-subscriptions': NewsletterSubscription;
    tickets: Ticket;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    cities: CitiesSelect<false> | CitiesSelect<true>;
    places: PlacesSelect<false> | PlacesSelect<true>;
    'pricing-plans': PricingPlansSelect<false> | PricingPlansSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    organizers: OrganizersSelect<false> | OrganizersSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    'claim-requests': ClaimRequestsSelect<false> | ClaimRequestsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    'attribute-groups': AttributeGroupsSelect<false> | AttributeGroupsSelect<true>;
    attributes: AttributesSelect<false> | AttributesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'post-categories': PostCategoriesSelect<false> | PostCategoriesSelect<true>;
    'newsletter-subscriptions': NewsletterSubscriptionsSelect<false> | NewsletterSubscriptionsSelect<true>;
    tickets: TicketsSelect<false> | TicketsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  surname: string;
  organizerName?: string | null;
  roles?: ('admin' | 'parent' | 'organizer')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug: string;
  icon: string;
  color: string;
  scopes: ('place' | 'event')[];
  /**
   * Kategorie wyróżnione są wyświetlane na stronie głównej
   */
  isFeatured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities".
 */
export interface City {
  id: number;
  name: string;
  slug?: string | null;
  isPopular?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "places".
 */
export interface Place {
  id: number;
  name: string;
  slug: string;
  plan?: ('free' | 'premium') | null;
  /**
   * Premium aktywne do tej daty. Przy subskrypcji aktualizowane automatycznie po każdym odnowieniu.
   */
  premiumExpiresAt?: string | null;
  category: number | Category;
  /**
   * Opcjonalny organizator/marka zarządzająca tym miejscem.
   */
  organizer?: (number | null) | Organizer;
  shortDescription?: string | null;
  longDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  logo?: (number | null) | Media;
  gallery?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Układaj bloki treści — tekst, zdjęcia, galerie. Widoczne tylko dla kont Premium.
   */
  storyBlocks?:
    | (
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'storyText';
          }
        | {
            image: number | Media;
            caption?: string | null;
            size?: ('full' | 'centered') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'storyImage';
          }
        | {
            images?:
              | {
                  image: number | Media;
                  id?: string | null;
                }[]
              | null;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'storyGallery';
          }
      )[]
    | null;
  street?: string | null;
  postalCode?: string | null;
  city: number | City;
  countryCode?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  phoneNumber?: string | null;
  email?: string | null;
  socialLinks?:
    | {
        platform?: ('Facebook' | 'Instagram' | 'Website' | 'TikTok') | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  rating?: number | null;
  reviewCount?: number | null;
  owner?: (number | null) | User;
  features?:
    | {
        attribute: number | Attribute;
        value: string;
        id?: string | null;
      }[]
    | null;
  isFree?: boolean | null;
  /**
   * Zdefiniuj dostępne rodzaje biletów i karnetów dla tego miejsca.
   */
  tickets?: (number | Ticket)[] | null;
  openingHours?:
    | {
        day: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday';
        hours: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Jeśli podasz ten link, na karcie obiektu pojawi się przycisk "Zarezerwuj pobyt"
   */
  affiliateBookingLink?: string | null;
  crmStatus?: ('new' | 'contacted' | 'interested' | 'rejected' | 'active') | null;
  crmNotes?: string | null;
  lastContacted?: string | null;
  /**
   * Zaznacz, aby nie wysyłać więcej wiadomości marketingowych do tego miejsca.
   */
  emailOptOut?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizers".
 */
export interface Organizer {
  id: number;
  name: string;
  owner?: (number | null) | User;
  slug: string;
  email?: string | null;
  phone?: string | null;
  website?: string | null;
  plan?: (number | null) | PricingPlan;
  billing?: {
    companyName?: string | null;
    nip?: string | null;
    address?: string | null;
    city?: string | null;
    postalCode?: string | null;
  };
  stripeCustomerId?: string | null;
  stripeSubscriptionId?: string | null;
  stripeSubscriptionStatus?:
    | ('active' | 'trialing' | 'incomplete' | 'incomplete_expired' | 'past_due' | 'canceled' | 'unpaid' | 'paused')
    | null;
  premiumExpiresAt?: string | null;
  collectionMethod?: ('charge_automatically' | 'send_invoice') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-plans".
 */
export interface PricingPlan {
  id: number;
  name: string;
  /**
   * ID Ceny REKURENCYJNEJ ze Stripe (np. price_12345)
   */
  stripePriceId_recurring?: string | null;
  /**
   * ID Ceny JEDNORAZOWEJ ze Stripe (np. price_54321)
   */
  stripePriceId_onetime?: string | null;
  /**
   * ID Ceny REKURENCYJNEJ rocznej ze Stripe
   */
  stripePriceId_annual_recurring?: string | null;
  /**
   * ID Ceny JEDNORAZOWEJ rocznej ze Stripe
   */
  stripePriceId_annual_onetime?: string | null;
  /**
   * Cena miesięczna w PLN (wersja subskrypcyjna)
   */
  planPrice_recurring: number;
  /**
   * Cena jednorazowa w PLN (wersja na 1 miesiąc)
   */
  planPrice_onetime: number;
  /**
   * Cena roczna w PLN (wersja subskrypcyjna)
   */
  planPrice_annual_recurring?: number | null;
  /**
   * Cena roczna w PLN (wersja na 1 rok)
   */
  planPrice_annual_onetime?: number | null;
  description: string;
  features?:
    | {
        feature?: string | null;
        id?: string | null;
      }[]
    | null;
  maxPlaces: number;
  maxEvents: number;
  /**
   * Zaznacz, jeśli ten plan daje dostęp do funkcji Premium. Używane przez system do synchronizacji statusu miejsc i wydarzeń.
   */
  isPremium?: boolean | null;
  isFeatured?: boolean | null;
  buttonText?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attributes".
 */
export interface Attribute {
  id: number;
  name: string;
  slug: string;
  type: 'text' | 'select' | 'multi-select' | 'boolean' | 'range';
  options?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  group: number | AttributeGroup;
  categories?: (number | Category)[] | null;
  /**
   * Kolejność wyświetlania wewnątrz grupy
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attribute-groups".
 */
export interface AttributeGroup {
  id: number;
  name: string;
  slug: string;
  /**
   * Kolejność wyświetlania (niższa liczba = wyżej)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tickets".
 */
export interface Ticket {
  id: number;
  name: string;
  price: number;
  description?: string | null;
  type?: ('one-time' | 'pass' | 'membership') | null;
  entries?: number | null;
  validityValue?: number | null;
  validityUnit?: ('days' | 'months' | 'years') | null;
  /**
   * Opcjonalny limit dostępności tego rodzaju biletu.
   */
  limit?: number | null;
  event?: (number | null) | Event;
  place?: (number | null) | Place;
  owner?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  slug: string;
  plan?: ('free' | 'premium') | null;
  startDate: string;
  endDate?: string | null;
  recurrence?: {
    isRecurring?: boolean | null;
    frequency?: ('daily' | 'weekly' | 'monthly') | null;
    interval?: number | null;
    daysOfWeek?: ('monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday')[] | null;
    recurrenceEndDate?: string | null;
  };
  isFree?: boolean | null;
  /**
   * Wybierz lub utwórz bilety dla tego wydarzenia.
   */
  tickets?: (number | Ticket)[] | null;
  ageRange?: string | null;
  place?: (number | null) | Place;
  category: number | Category;
  organizer: number | Organizer;
  logo?: (number | null) | Media;
  gallery?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  owner?: (number | null) | User;
  features?:
    | {
        attribute: number | Attribute;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  message: string;
  sourceType: 'places' | 'events';
  sourceId: string;
  status: 'new' | 'contacted' | 'enrolled' | 'rejected';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "claim-requests".
 */
export interface ClaimRequest {
  id: number;
  place: number | Place;
  user?: (number | null) | User;
  email: string;
  token: string;
  status: 'pending' | 'verified' | 'expired';
  expiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  place: number | Place;
  user: number | User;
  rating: number;
  content: string;
  reply?: string | null;
  replyDate?: string | null;
  status?: ('published' | 'pending' | 'rejected') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  slug: string;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  heroImage: number | Media;
  category: number | PostCategory;
  /**
   * Krótki opis widoczny na liście artykułów.
   */
  excerpt: string;
  content: (
    | {
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'richText';
      }
    | {
        title: string;
        description?: string | null;
        link: string;
        buttonLabel?: string | null;
        style?: ('rose' | 'blue' | 'dark') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'banner';
      }
    | {
        title?: string | null;
        items: (
          | {
              relationTo: 'places';
              value: number | Place;
            }
          | {
              relationTo: 'events';
              value: number | Event;
            }
        )[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'relatedItems';
      }
  )[];
  slug: string;
  publishedDate?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-categories".
 */
export interface PostCategory {
  id: number;
  title: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscriptions".
 */
export interface NewsletterSubscription {
  id: number;
  email: string;
  name?: string | null;
  city?: string | null;
  /**
   * Zgoda na otrzymywanie newslettera
   */
  consent: boolean;
  status?: ('active' | 'unsubscribed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'cities';
        value: number | City;
      } | null)
    | ({
        relationTo: 'places';
        value: number | Place;
      } | null)
    | ({
        relationTo: 'pricing-plans';
        value: number | PricingPlan;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'organizers';
        value: number | Organizer;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null)
    | ({
        relationTo: 'claim-requests';
        value: number | ClaimRequest;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'attribute-groups';
        value: number | AttributeGroup;
      } | null)
    | ({
        relationTo: 'attributes';
        value: number | Attribute;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'post-categories';
        value: number | PostCategory;
      } | null)
    | ({
        relationTo: 'newsletter-subscriptions';
        value: number | NewsletterSubscription;
      } | null)
    | ({
        relationTo: 'tickets';
        value: number | Ticket;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  surname?: T;
  organizerName?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  icon?: T;
  color?: T;
  scopes?: T;
  isFeatured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities_select".
 */
export interface CitiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  isPopular?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "places_select".
 */
export interface PlacesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  plan?: T;
  premiumExpiresAt?: T;
  category?: T;
  organizer?: T;
  shortDescription?: T;
  longDescription?: T;
  logo?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  storyBlocks?:
    | T
    | {
        storyText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        storyImage?:
          | T
          | {
              image?: T;
              caption?: T;
              size?: T;
              id?: T;
              blockName?: T;
            };
        storyGallery?:
          | T
          | {
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              caption?: T;
              id?: T;
              blockName?: T;
            };
      };
  street?: T;
  postalCode?: T;
  city?: T;
  countryCode?: T;
  latitude?: T;
  longitude?: T;
  phoneNumber?: T;
  email?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  rating?: T;
  reviewCount?: T;
  owner?: T;
  features?:
    | T
    | {
        attribute?: T;
        value?: T;
        id?: T;
      };
  isFree?: T;
  tickets?: T;
  openingHours?:
    | T
    | {
        day?: T;
        hours?: T;
        id?: T;
      };
  affiliateBookingLink?: T;
  crmStatus?: T;
  crmNotes?: T;
  lastContacted?: T;
  emailOptOut?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-plans_select".
 */
export interface PricingPlansSelect<T extends boolean = true> {
  name?: T;
  stripePriceId_recurring?: T;
  stripePriceId_onetime?: T;
  stripePriceId_annual_recurring?: T;
  stripePriceId_annual_onetime?: T;
  planPrice_recurring?: T;
  planPrice_onetime?: T;
  planPrice_annual_recurring?: T;
  planPrice_annual_onetime?: T;
  description?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  maxPlaces?: T;
  maxEvents?: T;
  isPremium?: T;
  isFeatured?: T;
  buttonText?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  plan?: T;
  startDate?: T;
  endDate?: T;
  recurrence?:
    | T
    | {
        isRecurring?: T;
        frequency?: T;
        interval?: T;
        daysOfWeek?: T;
        recurrenceEndDate?: T;
      };
  isFree?: T;
  tickets?: T;
  ageRange?: T;
  place?: T;
  category?: T;
  organizer?: T;
  logo?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  description?: T;
  owner?: T;
  features?:
    | T
    | {
        attribute?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizers_select".
 */
export interface OrganizersSelect<T extends boolean = true> {
  name?: T;
  owner?: T;
  slug?: T;
  email?: T;
  phone?: T;
  website?: T;
  plan?: T;
  billing?:
    | T
    | {
        companyName?: T;
        nip?: T;
        address?: T;
        city?: T;
        postalCode?: T;
      };
  stripeCustomerId?: T;
  stripeSubscriptionId?: T;
  stripeSubscriptionStatus?: T;
  premiumExpiresAt?: T;
  collectionMethod?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  message?: T;
  sourceType?: T;
  sourceId?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "claim-requests_select".
 */
export interface ClaimRequestsSelect<T extends boolean = true> {
  place?: T;
  user?: T;
  email?: T;
  token?: T;
  status?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  place?: T;
  user?: T;
  rating?: T;
  content?: T;
  reply?: T;
  replyDate?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attribute-groups_select".
 */
export interface AttributeGroupsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attributes_select".
 */
export interface AttributesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  options?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  group?: T;
  categories?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  slug?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  category?: T;
  excerpt?: T;
  content?:
    | T
    | {
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        banner?:
          | T
          | {
              title?: T;
              description?: T;
              link?: T;
              buttonLabel?: T;
              style?: T;
              id?: T;
              blockName?: T;
            };
        relatedItems?:
          | T
          | {
              title?: T;
              items?: T;
              id?: T;
              blockName?: T;
            };
      };
  slug?: T;
  publishedDate?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-categories_select".
 */
export interface PostCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscriptions_select".
 */
export interface NewsletterSubscriptionsSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  city?: T;
  consent?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tickets_select".
 */
export interface TicketsSelect<T extends boolean = true> {
  name?: T;
  price?: T;
  description?: T;
  type?: T;
  entries?: T;
  validityValue?: T;
  validityUnit?: T;
  limit?: T;
  event?: T;
  place?: T;
  owner?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}